import { useEffect, useState } from 'react';
import {
  integrityApi,
  type IntegrityStatus,
  type IntegrityBlockItem,
  type TamperResponse,
  type VerifyResponse,
} from '../services/api';
import {
  ShieldCheck,
  ShieldAlert,
  Lock,
  Link,
  RotateCcw,
  AlertTriangle,
  CheckCircle2,
  Database,
  ArrowRight,
  Download,
  X,
  Info,
  FileCheck,
  Hash,
  FileSpreadsheet,
} from 'lucide-react';

interface EvidenceModalProps {
  status: IntegrityStatus | null;
  onClose: () => void;
}

function EvidenceReportModal({ status, onClose }: EvidenceModalProps) {
  if (!status) return null;
  const activeStatus = status;

  const generatedAt = new Date().toISOString();
  const reportId = `EV-REP-${Date.now().toString(36).toUpperCase()}`;

  function handleDownload() {
    const reportData = {
      reportId,
      generatedAt,
      system: 'EcoWatch Industrial Environmental & Safety Platform',
      theme: 'Verdant Green Technology',
      subsystem: 'Evidence & Integrity Engine',
      auditStatus: activeStatus.verified ? 'VERIFIED_PRISTINE' : 'INTEGRITY_BREACH_DETECTED',
      epochDuration: activeStatus.epoch,
      cryptographicStandard: activeStatus.chain,
      anchoringMechanism: activeStatus.anchor,
      totalBlocks: activeStatus.blockCount,
      blocks: activeStatus.blocks.map((b) => ({
        blockIndex: b.index,
        timeWindow: `${b.startTime} - ${b.endTime}`,
        sampleCount: b.sampleCount,
        blockHash: b.hash,
        previousHash: b.previousHash,
        anchorHash: b.anchorHash,
        tampered: b.tampered,
        payload: b.payload,
      })),
      disclaimer:
        'This document is a prototype cryptographic evidence summary generated by EcoWatch. For demonstration and audit-trail verification purposes only.',
    };

    const blob = new Blob([JSON.stringify(reportData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${reportId}-evidence-report.json`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
      <div className="relative w-full max-w-3xl rounded-3xl border border-[var(--line)] bg-[#ffffff] p-7 shadow-2xl space-y-6 max-h-[90vh] overflow-y-auto">
        <div className="flex items-start justify-between border-b border-[var(--line)] pb-4">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[#6fa350]/15 text-[#4f7a38]">
              <FileCheck size={22} />
            </div>
            <div>
              <h3 className="font-serif text-2xl font-bold text-[#25352b]">
                Pre-Audit Telemetry Evidence Report
              </h3>
              <p className="font-mono text-xs text-[#6d7d70] mt-0.5">
                Cryptographic manifest for ESG / BRSR sustainability assurance
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="rounded-xl p-2 text-[#6d7d70] hover:bg-slate-100 hover:text-[#25352b] transition-colors"
          >
            <X size={20} />
          </button>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 font-mono text-xs">
          <div className="rounded-2xl border border-[var(--line)] bg-[#fbfbf9] p-3.5">
            <span className="text-[#6d7d70] text-[10px] block uppercase font-semibold">Report ID:</span>
            <span className="text-[#4f7a38] font-bold text-sm">{reportId}</span>
          </div>
          <div className="rounded-2xl border border-[var(--line)] bg-[#fbfbf9] p-3.5">
            <span className="text-[#6d7d70] text-[10px] block uppercase font-semibold">Generated:</span>
            <span className="text-[#25352b] font-medium">{new Date(generatedAt).toLocaleTimeString()}</span>
          </div>
          <div className="rounded-2xl border border-[var(--line)] bg-[#fbfbf9] p-3.5">
            <span className="text-[#6d7d70] text-[10px] block uppercase font-semibold">Sealed Epochs:</span>
            <span className="text-[#25352b] font-bold text-sm">{activeStatus.blockCount} blocks</span>
          </div>
          <div className="rounded-2xl border border-[var(--line)] bg-[#fbfbf9] p-3.5">
            <span className="text-[#6d7d70] text-[10px] block uppercase font-semibold">Audit Status:</span>
            <span className={`font-bold ${activeStatus.verified ? 'text-[#4f7a38]' : 'text-red-600'}`}>
              {activeStatus.verified ? 'PASS (VERIFIED)' : 'FAIL (ALTERED)'}
            </span>
          </div>
        </div>

        <div className="space-y-3">
          <h4 className="font-mono text-xs uppercase tracking-wider text-[#4f7a38] font-bold flex items-center gap-2">
            <Database size={14} />
            <span>Block Hash &amp; Protected Anchor Manifest</span>
          </h4>
          <div className="rounded-2xl border border-[var(--line)] bg-[#fbfbf9] divide-y divide-[var(--line)] font-mono text-xs max-h-60 overflow-y-auto">
            {activeStatus.blocks.map((b) => (
              <div key={b.index} className="p-3.5 space-y-1.5 bg-white first:rounded-t-2xl last:rounded-b-2xl">
                <div className="flex items-center justify-between">
                  <span className="font-bold text-[#25352b]">
                    Block #{b.index} ({b.sampleCount} samples)
                  </span>
                  <span
                    className={`rounded-full px-2.5 py-0.5 text-[9px] font-bold uppercase border ${
                      b.tampered
                        ? 'bg-red-50 text-red-700 border-red-200'
                        : 'bg-[#6fa350]/15 text-[#4f7a38] border-[#6fa350]/30'
                    }`}
                  >
                    {b.tampered ? 'TAMPERED / MISMATCH' : 'CRYPTOGRAPHICALLY SEALED'}
                  </span>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-2 text-[11px] pt-1">
                  <div className="bg-[#fbfbf9] p-2 rounded-xl border border-[var(--line)]">
                    <span className="text-[#6d7d70] text-[9px] block uppercase font-semibold">SHA-256 Block Hash:</span>
                    <code className="text-[#4f7a38] block truncate font-bold">{b.hash}</code>
                  </div>
                  <div className="bg-[#fbfbf9] p-2 rounded-xl border border-[var(--line)]">
                    <span className="text-[#6d7d70] text-[9px] block uppercase font-semibold">Append-Only Anchor:</span>
                    <code className="text-[#25352b] block truncate font-bold">{b.anchorHash ?? 'NONE'}</code>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="rounded-2xl border border-slate-200 bg-[#fbfbf9] p-4 flex items-start gap-3 font-mono text-[11px] text-[#6d7d70]">
          <Info size={16} className="text-[#6fa350] flex-shrink-0 mt-0.5" />
          <p className="leading-relaxed">
            <strong className="text-[#25352b]">Prototype Disclaimer:</strong> This report demonstrates cryptographic
            tamper-evidence through linked SHA-256 blocks and append-only hash anchoring for industrial audit readiness.
            This is an academic &amp; hackathon engineering prototype, not a legal or regulatory certification.
          </p>
        </div>

        <div className="flex items-center justify-end gap-3 pt-2">
          <button
            onClick={onClose}
            className="rounded-xl border border-slate-300 px-4 py-2.5 font-mono text-xs font-semibold text-[#6d7d70] hover:bg-slate-100 transition-colors"
          >
            Close
          </button>
          <button
            onClick={handleDownload}
            className="flex items-center gap-2 rounded-xl bg-[#6fa350] hover:bg-[#4f7a38] px-5 py-2.5 font-mono text-xs font-bold text-white transition-all shadow-md"
          >
            <Download size={15} />
            <span>Download Evidence Pack (.json)</span>
          </button>
        </div>
      </div>
    </div>
  );
}

export function EvidenceIntegrityCenter() {
  const [busy, setBusy] = useState<string | null>(null);
  const [status, setStatus] = useState<IntegrityStatus | null>(null);
  const [selectedBlock, setSelectedBlock] = useState<IntegrityBlockItem | null>(null);
  const [tamperFeedback, setTamperFeedback] = useState<TamperResponse | null>(null);
  const [verifyFeedback, setVerifyFeedback] = useState<VerifyResponse | null>(null);
  const [showEvidenceReport, setShowEvidenceReport] = useState(false);
  const [tamperStep, setTamperStep] = useState<'idle' | 'hash_mismatch' | 'anchor_mismatch' | 'detected'>('idle');

  async function loadStatus() {
    try {
      const data = await integrityApi.status();
      setStatus(data);
      if (data.blocks.length > 0 && !selectedBlock) {
        setSelectedBlock(data.blocks[1] ?? data.blocks[0]);
      }
    } catch {
      /* ignore */
    }
  }

  useEffect(() => {
    void loadStatus();
  }, []);

  async function handleVerify() {
    setBusy('verify');
    setTamperFeedback(null);
    try {
      const res = await integrityApi.verify();
      setVerifyFeedback(res);
      await loadStatus();
    } finally {
      setBusy(null);
    }
  }

  async function handleSimulateTampering() {
    setBusy('tamper');
    setVerifyFeedback(null);
    setTamperStep('hash_mismatch');

    try {
      // Step 1: Simulate direct edit of historical telemetry in Block #2
      const res = await integrityApi.tamperDirect(2);
      setTamperFeedback(res);
      await loadStatus();

      // Animate visual detection pipeline: HASH MISMATCH -> ANCHOR MISMATCH -> TAMPERING DETECTED
      setTimeout(() => setTamperStep('anchor_mismatch'), 800);
      setTimeout(() => setTamperStep('detected'), 1600);
    } finally {
      setBusy(null);
    }
  }

  async function handleResetBaseline() {
    setBusy('reset');
    setTamperFeedback(null);
    setVerifyFeedback(null);
    setTamperStep('idle');
    try {
      await integrityApi.reset();
      await loadStatus();
    } finally {
      setBusy(null);
    }
  }

  const lastBlock = status?.blocks.at(-1);

  return (
    <div className="space-y-6">
      {/* ── Evidence Report Modal ── */}
      {showEvidenceReport && (
        <EvidenceReportModal status={status} onClose={() => setShowEvidenceReport(false)} />
      )}

      {/* ── EVIDENCE & INTEGRITY CENTER MAIN CONTAINER ── */}
      <div className="rounded-2xl border border-[var(--line)] bg-[#ffffff]/95 p-6 sm:p-7 shadow-verdant space-y-6">
        {/* Header Bar */}
        <div className="flex flex-wrap items-start justify-between gap-4 pb-5 border-b border-[var(--line)]">
          <div className="space-y-1">
            <div className="flex items-center gap-2.5">
              <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#6fa350]/15 text-[#4f7a38]">
                <ShieldCheck size={20} />
              </div>
              <h2 className="font-serif text-2xl font-bold text-[#25352b] tracking-tight">
                Evidence &amp; Integrity Center
              </h2>
            </div>
            <p className="font-mono text-xs text-[#6d7d70] max-w-2xl leading-relaxed">
              Cryptographic SHA-256 hash-chain verification and append-only anchoring for tamper-evident industrial
              telemetry records and ESG/BRSR pre-audit verification.
            </p>
          </div>

          {/* Overall Status Badge */}
          <div className="flex items-center gap-3">
            <span
              className={`rounded-2xl border px-4 py-2 font-mono text-xs font-bold uppercase tracking-wider flex items-center gap-2 shadow-sm ${
                status?.verified
                  ? 'border-[#6fa350]/40 bg-[#6fa350]/15 text-[#4f7a38]'
                  : 'border-red-400 bg-red-50 text-red-700 animate-pulse'
              }`}
            >
              {status?.verified ? (
                <>
                  <CheckCircle2 size={16} className="text-[#4f7a38]" />
                  <span>INTEGRITY VERIFIED</span>
                </>
              ) : (
                <>
                  <AlertTriangle size={16} className="text-red-600" />
                  <span>TAMPERING DETECTED</span>
                </>
              )}
            </span>
          </div>
        </div>

        {/* ── Key Metrics Overview ── */}
        <div className="grid grid-cols-2 gap-3.5 sm:grid-cols-4">
          {/* Telemetry Records */}
          <div className="rounded-2xl border border-[var(--line)] bg-[#fbfbf9] p-4 shadow-sm">
            <div className="flex items-center justify-between text-[#6d7d70] mb-1">
              <span className="font-mono text-[10px] uppercase tracking-[0.12em] font-semibold">
                Telemetry Records
              </span>
              <Database size={14} className="text-[#4f7a38]" />
            </div>
            <p className="font-serif text-2xl font-bold text-[#25352b]">
              {status?.blockCount ? status.blockCount * 60 : 0}{' '}
              <span className="font-sans text-xs text-[#6d7d70] font-normal">samples</span>
            </p>
            <p className="font-mono text-[10px] text-[#6d7d70] mt-1">
              {status?.blockCount ?? 0} sealed 5-min epochs
            </p>
          </div>

          {/* SHA-256 Hash Chain */}
          <div className="rounded-2xl border border-[var(--line)] bg-[#fbfbf9] p-4 shadow-sm">
            <div className="flex items-center justify-between text-[#6d7d70] mb-1">
              <span className="font-mono text-[10px] uppercase tracking-[0.12em] font-semibold">
                Hash-Chain Status
              </span>
              <Link size={14} className="text-[#4f7a38]" />
            </div>
            <p className="font-serif text-2xl font-bold text-[#4f7a38]">
              {status?.tampered ? 'BROKEN' : 'SHA-256 LINKED'}
            </p>
            <p className="font-mono text-[10px] text-[#6d7d70] mt-1">Cryptographic previous_hash</p>
          </div>

          {/* Anchored Hash */}
          <div className="rounded-2xl border border-[var(--line)] bg-[#fbfbf9] p-4 shadow-sm">
            <div className="flex items-center justify-between text-[#6d7d70] mb-1">
              <span className="font-mono text-[10px] uppercase tracking-[0.12em] font-semibold">
                Anchored Hash
              </span>
              <Lock size={14} className="text-[#8fc46a]" />
            </div>
            <p className="font-mono text-xs font-bold text-[#25352b] truncate mt-1">
              {lastBlock?.anchorHash ? `${lastBlock.anchorHash.slice(0, 14)}…` : 'Protected'}
            </p>
            <p className="font-mono text-[10px] text-[#6d7d70] mt-1">Append-only anchor reference</p>
          </div>

          {/* Last Verified Block */}
          <div className="rounded-2xl border border-[var(--line)] bg-[#fbfbf9] p-4 shadow-sm">
            <div className="flex items-center justify-between text-[#6d7d70] mb-1">
              <span className="font-mono text-[10px] uppercase tracking-[0.12em] font-semibold">
                Last Verified Block
              </span>
              <FileCheck size={14} className="text-[#4f7a38]" />
            </div>
            <p className="font-serif text-2xl font-bold text-[#25352b]">
              Block #{status?.lastBlock ?? '—'}
            </p>
            <p className="font-mono text-[10px] text-[#4f7a38] font-semibold mt-1">Epoch verified &amp; sealed</p>
          </div>
        </div>

        {/* ── Action Buttons Bar ── */}
        <div className="rounded-2xl border border-[var(--line)] bg-[#fbfbf9] p-5 space-y-4 shadow-sm">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div className="flex flex-wrap items-center gap-2.5">
              {/* Verify History */}
              <button
                disabled={busy !== null}
                onClick={() => void handleVerify()}
                className="flex items-center gap-2 rounded-xl bg-[#6fa350] hover:bg-[#4f7a38] px-4 py-2.5 font-mono text-xs font-bold text-white transition-all shadow-sm disabled:opacity-50 cursor-pointer"
              >
                <ShieldCheck size={15} />
                <span>Verify History</span>
              </button>

              {/* Generate Evidence Report */}
              <button
                onClick={() => setShowEvidenceReport(true)}
                className="flex items-center gap-2 rounded-xl bg-white border border-[var(--line)] hover:bg-[#f3f7f0] text-[#4f7a38] px-4 py-2.5 font-mono text-xs font-bold transition-all shadow-sm cursor-pointer"
              >
                <FileSpreadsheet size={15} />
                <span>Generate Evidence Report</span>
              </button>

              {/* Simulate Tampering */}
              <button
                disabled={busy !== null}
                onClick={() => void handleSimulateTampering()}
                className="flex items-center gap-2 rounded-xl bg-red-50 border border-red-200 hover:bg-red-100 text-red-700 px-4 py-2.5 font-mono text-xs font-bold transition-all shadow-sm disabled:opacity-50 cursor-pointer"
              >
                <ShieldAlert size={15} />
                <span>Simulate Tampering</span>
              </button>
            </div>

            {/* Reset / Restore */}
            <button
              disabled={busy !== null}
              onClick={() => void handleResetBaseline()}
              className="flex items-center gap-2 rounded-xl bg-white border border-slate-300 hover:bg-slate-100 px-4 py-2.5 font-mono text-xs font-semibold text-[#6d7d70] hover:text-[#25352b] transition-all disabled:opacity-50 cursor-pointer"
            >
              <RotateCcw size={14} className={busy === 'reset' ? 'animate-spin' : ''} />
              <span>Reset / Restore</span>
            </button>
          </div>

          {/* ── Tampering Live Progression Banner (HASH MISMATCH → ANCHOR MISMATCH → TAMPERING DETECTED) ── */}
          {tamperFeedback && (
            <div className="rounded-2xl border border-red-300 bg-red-50 p-5 space-y-3.5 shadow-sm">
              <div className="flex items-center justify-between">
                <span className="font-mono text-xs font-bold text-red-800 flex items-center gap-2">
                  <ShieldAlert size={16} className="text-red-600 animate-pulse" />
                  <span>Live Tamper Detection Progression</span>
                </span>
                <span className="font-mono text-[10px] text-red-700 bg-red-100 border border-red-200 rounded-lg px-2.5 py-1 font-bold uppercase">
                  Attack Target: Block #{tamperFeedback.blockIndex}
                </span>
              </div>

              {/* Progression Step Pills */}
              <div className="flex flex-wrap items-center gap-2.5 font-mono text-xs">
                <div
                  className={`flex items-center gap-1.5 rounded-xl px-3.5 py-2 border font-bold shadow-sm ${
                    tamperStep !== 'idle'
                      ? 'border-red-400 bg-red-600 text-white'
                      : 'border-slate-200 bg-white text-slate-400'
                  }`}
                >
                  <AlertTriangle size={14} />
                  <span>HASH MISMATCH</span>
                </div>
                <ArrowRight size={15} className="text-red-400" />
                <div
                  className={`flex items-center gap-1.5 rounded-xl px-3.5 py-2 border font-bold shadow-sm ${
                    tamperStep === 'anchor_mismatch' || tamperStep === 'detected'
                      ? 'border-amber-400 bg-amber-500 text-white'
                      : 'border-slate-200 bg-white text-slate-400'
                  }`}
                >
                  <Lock size={14} />
                  <span>ANCHOR MISMATCH</span>
                </div>
                <ArrowRight size={15} className="text-red-400" />
                <div
                  className={`flex items-center gap-1.5 rounded-xl px-3.5 py-2 border font-bold shadow-sm ${
                    tamperStep === 'detected'
                      ? 'border-red-800 bg-red-800 text-white font-black tracking-wider'
                      : 'border-slate-200 bg-white text-slate-400'
                  }`}
                >
                  <ShieldAlert size={14} />
                  <span>TAMPERING DETECTED</span>
                </div>
              </div>

              <div className="text-xs font-mono text-red-900 leading-relaxed bg-white p-3.5 rounded-xl border border-red-200 shadow-sm">
                <p>
                  <strong>Breach Details:</strong> {tamperFeedback.simulatedEdit}
                </p>
                <p className="mt-1 text-slate-600 text-[11px]">
                  Recalculated payload hash differs from original sealed block hash. The protected append-only anchor
                  preserved the immutable reference and rejected the altered record.
                </p>
              </div>
            </div>
          )}

          {/* Verification Feedback Banner */}
          {verifyFeedback && (
            <div
              className={`rounded-2xl border p-4 font-mono text-xs flex items-start gap-3 shadow-sm ${
                verifyFeedback.verified
                  ? 'border-[#6fa350]/40 bg-[#6fa350]/10 text-[#4f7a38]'
                  : 'border-red-300 bg-red-50 text-red-800'
              }`}
            >
              {verifyFeedback.verified ? (
                <CheckCircle2 size={18} className="text-[#4f7a38] mt-0.5 flex-shrink-0" />
              ) : (
                <AlertTriangle size={18} className="text-red-600 mt-0.5 flex-shrink-0" />
              )}
              <div className="space-y-0.5">
                <p className="font-bold">{verifyFeedback.reason}</p>
                <p className="text-slate-600 text-[11px]">{verifyFeedback.details}</p>
              </div>
            </div>
          )}
        </div>

        {/* ── Sealed Telemetry Records (5-Min Sealed Blocks) ── */}
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <span className="font-mono text-xs uppercase tracking-wider text-[#4f7a38] font-bold flex items-center gap-2">
              <Hash size={15} />
              <span>Sealed Telemetry Records (5-Minute Cryptographic Epochs)</span>
            </span>
            <span className="font-mono text-[10px] text-[#6d7d70]">Click any epoch to inspect payload</span>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3.5">
            {status?.blocks.map((block, idx) => {
              const isSelected = selectedBlock?.index === block.index;
              const isCompromised = block.isPayloadAltered || block.isAnchorMismatch || block.tampered;

              return (
                <div
                  key={block.index}
                  onClick={() => setSelectedBlock(block)}
                  className={`cursor-pointer rounded-2xl border p-4 transition-all relative shadow-sm ${
                    isCompromised
                      ? 'border-red-400 bg-red-50/70 ring-2 ring-red-400/40'
                      : isSelected
                      ? 'border-[#6fa350] bg-[#f4f9f0] ring-2 ring-[#6fa350]/30'
                      : 'border-[var(--line)] bg-white hover:border-[#6fa350]/40'
                  }`}
                >
                  {idx > 0 && (
                    <div className="hidden lg:block absolute -left-3 top-1/2 -translate-y-1/2 text-[#8fc46a] z-10">
                      <ArrowRight size={14} />
                    </div>
                  )}

                  <div className="flex items-center justify-between mb-2">
                    <span className="font-serif text-base font-bold text-[#25352b]">Block #{block.index}</span>
                    <span
                      className={`rounded-full px-2.5 py-0.5 font-mono text-[9px] font-bold uppercase border ${
                        isCompromised
                          ? 'bg-red-100 text-red-800 border-red-200'
                          : 'bg-[#6fa350]/15 text-[#4f7a38] border-[#6fa350]/30'
                      }`}
                    >
                      {isCompromised ? 'TAMPERED' : 'SEALED'}
                    </span>
                  </div>

                  <div className="space-y-1.5 font-mono text-[11px]">
                    <div className="flex justify-between text-[#6d7d70]">
                      <span>Air Quality:</span>
                      <span className={block.tampered ? 'text-red-600 font-bold' : 'text-[#25352b] font-medium'}>
                        {block.payload.airQuality ?? '—'} AQI
                      </span>
                    </div>
                    <div className="flex justify-between text-[#6d7d70]">
                      <span>Current / Power:</span>
                      <span className="text-[#25352b]">
                        {block.payload.current ?? 0} A · {block.payload.estimatedPowerW ?? 0} W
                      </span>
                    </div>

                    <div className="pt-2 border-t border-[var(--line)] space-y-1 text-[10px]">
                      <div>
                        <span className="text-[#6d7d70] block text-[9px] uppercase font-semibold">PREV HASH:</span>
                        <code className="text-slate-500 block truncate">{block.shortPreviousHash}…</code>
                      </div>
                      <div>
                        <span className="text-[#6d7d70] block text-[9px] uppercase font-semibold">BLOCK HASH:</span>
                        <code
                          className={`block truncate font-bold ${
                            isCompromised ? 'text-red-600' : 'text-[#4f7a38]'
                          }`}
                        >
                          {block.shortHash}…
                        </code>
                      </div>
                      <div>
                        <span className="text-[#6d7d70] block text-[9px] uppercase font-semibold">ANCHOR HASH:</span>
                        <code
                          className={`block truncate font-bold ${
                            block.isAnchorMismatch ? 'text-amber-600' : 'text-[#25352b]'
                          }`}
                        >
                          {block.shortAnchorHash ?? 'UNANCHORED'}…
                        </code>
                      </div>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* ── Auditable Payload Inspector (Selected Block) ── */}
        {selectedBlock && (
          <div className="rounded-2xl border border-[var(--line)] bg-[#fbfbf9] p-5 space-y-3.5 shadow-sm">
            <div className="flex items-center justify-between">
              <span className="font-serif text-lg font-bold text-[#4f7a38] flex items-center gap-2">
                <Database size={16} />
                <span>Auditable Telemetry Payload Inspector — Block #{selectedBlock.index}</span>
              </span>
              <span className="font-mono text-[11px] text-[#6d7d70]">
                {new Date(selectedBlock.startTime).toLocaleTimeString()} –{' '}
                {new Date(selectedBlock.endTime).toLocaleTimeString()}
              </span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-3.5 text-xs font-mono">
              <div className="bg-white border border-[var(--line)] rounded-xl p-4 space-y-2 shadow-sm">
                <p className="text-[#4f7a38] text-[11px] uppercase tracking-wider font-bold mb-1">
                  Hashed Telemetry Attributes
                </p>
                <div className="flex justify-between py-1 border-b border-[var(--line)]">
                  <span className="text-[#6d7d70]">Air Quality / AQI:</span>{' '}
                  <span className={selectedBlock.tampered ? 'text-red-600 font-bold' : 'text-[#25352b] font-semibold'}>
                    {selectedBlock.payload.airQuality}{' '}
                    {selectedBlock.tampered && `(Altered from original: ${selectedBlock.originalValue})`}
                  </span>
                </div>
                <div className="flex justify-between py-1 border-b border-[var(--line)]">
                  <span className="text-[#6d7d70]">Current (A):</span>{' '}
                  <span className="text-[#25352b] font-semibold">{selectedBlock.payload.current} A</span>
                </div>
                <div className="flex justify-between py-1 border-b border-[var(--line)]">
                  <span className="text-[#6d7d70]">Estimated Power (W):</span>{' '}
                  <span className="text-[#25352b] font-semibold">{selectedBlock.payload.estimatedPowerW} W</span>
                </div>
                <div className="flex justify-between py-1 border-b border-[var(--line)]">
                  <span className="text-[#6d7d70]">Water Leak Sensor:</span>{' '}
                  <span className="text-[#25352b] font-semibold">
                    {selectedBlock.payload.waterLeak ? 'TRUE (LEAK)' : 'FALSE (NORMAL)'}
                  </span>
                </div>
                <div className="flex justify-between py-1">
                  <span className="text-[#6d7d70]">Fire / Thermal Sensor:</span>{' '}
                  <span className="text-[#25352b] font-semibold">
                    {selectedBlock.payload.fireDetected ? 'TRUE (FIRE)' : 'FALSE (NORMAL)'}
                  </span>
                </div>
              </div>

              <div className="bg-white border border-[var(--line)] rounded-xl p-4 space-y-2.5 shadow-sm">
                <p className="text-[#4f7a38] text-[11px] uppercase tracking-wider font-bold mb-1">
                  Cryptographic Integrity Footprints
                </p>
                <div>
                  <span className="text-[#6d7d70] text-[10px] block uppercase font-semibold">Full SHA-256 Block Hash:</span>
                  <code className="text-[#4f7a38] text-[11px] break-all block font-bold mt-0.5">{selectedBlock.hash}</code>
                </div>
                <div>
                  <span className="text-[#6d7d70] text-[10px] block uppercase font-semibold">Previous Block Hash (Link):</span>
                  <code className="text-slate-600 text-[11px] break-all block mt-0.5">{selectedBlock.previousHash}</code>
                </div>
                <div>
                  <span className="text-[#6d7d70] text-[10px] block uppercase font-semibold">Protected Append-Only Anchor:</span>
                  <code
                    className={`text-[11px] break-all block font-bold mt-0.5 ${
                      selectedBlock.isAnchorMismatch ? 'text-amber-600' : 'text-[#25352b]'
                    }`}
                  >
                    {selectedBlock.anchorHash ?? 'None'}
                  </code>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* ── System Disclaimer ── */}
        <div className="rounded-2xl border border-slate-200 bg-[#fbfbf9] p-4 flex items-start gap-3 shadow-sm">
          <Info size={16} className="text-[#6fa350] flex-shrink-0 mt-0.5" />
          <p className="font-mono text-[11px] text-[#6d7d70] leading-relaxed">
            <strong className="text-[#25352b]">Prototype Evidence &amp; Integrity System:</strong> Demonstrates
            tamper-evident SHA-256 hash chaining and protected append-only anchoring for industrial audit trails.
            Provides cryptographic verification evidence of historical telemetry records; this is an engineering prototype and not a
            certified legal or regulatory compliance system.
          </p>
        </div>
      </div>
    </div>
  );
}
