/**
 * EcoGen AI — Local Multimodal Vision & Sensor Inspection Provider
 * ─────────────────────────────────────────────────────────────────────────────
 * Intelligent, context-aware local industrial inspection analyzer.
 * Performs deep visual heuristic analysis on uploaded equipment photos,
 * cross-referencing inspector notes, component tags, and multi-sensor telemetry
 * to predict risks such as CO2 / toxic gas leaks, water / coolant leaks,
 * thermal overload, and mechanical deterioration.
 */

import fs from 'fs';
import path from 'path';
import type {
  AIInspectionProvider,
  AIInspectionInput,
  AIAnalysisResponse,
  AIInspectionResult,
  VisualIndicator,
  EvidenceItem,
  AIRiskLevel,
} from '../types';
import { buildError } from '../utils/responseValidator';
import { uploadStore } from '../../services/uploadStore';
import { visionMLBridge } from '../ml/VisionMLBridge';

const DISCLAIMER =
  'This is an AI-assisted predictive maintenance assessment generated by the EcoWatch Industrial Vision Engine. ' +
  'It synthesizes visual evidence, environmental sensor telemetry, and historical maintenance patterns ' +
  'to provide early failure warnings. Safety decisions should be validated by certified plant engineers.';

export class MockAIInspectionProvider implements AIInspectionProvider {
  readonly name = 'EcoWatch Industrial Vision Engine v2.4';

  private readonly latencyMs: number;
  private readonly forceError: boolean;

  constructor() {
    this.latencyMs  = parseInt(process.env.MOCK_AI_LATENCY_MS ?? '400', 10);
    this.forceError = process.env.MOCK_AI_FORCE_ERROR === 'true';
  }

  isAvailable(): boolean { return true; }

  async analyzeInspection(input: AIInspectionInput): Promise<AIAnalysisResponse> {
    if (this.latencyMs > 0) {
      await new Promise((r) => setTimeout(r, this.latencyMs));
    }

    if (this.forceError) {
      return buildError('PROVIDER_UNAVAILABLE', '[Vision Engine] Forced error for testing.', false);
    }

    // 1. Analyze Uploaded Images with Vision ML Models
    const imageInfo: Array<{ storagePath: string; exists: boolean; sizeBytes: number; filename: string; absPath: string }> = [];
    for (const ref of input.imageReferences) {
      try {
        if (uploadStore.exists(ref)) {
          const absPath = uploadStore.resolve(ref);
          const stat = fs.statSync(absPath);
          imageInfo.push({
            storagePath: ref,
            exists: true,
            sizeBytes: stat.size,
            filename: path.basename(ref),
            absPath,
          });
        }
      } catch {
        // Non-fatal
      }
    }

    // Run Trained Vision ML Models on uploaded image
    let visionCorrosionResult: any = null;
    let visionLeakResult: any = null;

    if (imageInfo.length > 0) {
      try {
        const visionResult = await visionMLBridge.analyzeImage(imageInfo[0].absPath);
        visionCorrosionResult = visionResult.corrosion;
        visionLeakResult = visionResult.waterLeak;
      } catch (e) {
        console.warn('[VisionML] Model analysis fallback:', e);
      }
    }

    const leakConf = visionLeakResult?.prediction === 'leak' ? (visionLeakResult?.confidence ?? 0) : 0;
    const corrConf = visionCorrosionResult?.prediction === 'corrosion' ? (visionCorrosionResult?.confidence ?? 0) : 0;

    const visionDetectedLeak = leakConf >= 0.55;
    const visionDetectedCorrosion = corrConf >= 0.55;

    const hasImages = imageInfo.length > 0;
    const hasNotes = input.inspectorNotes.trim().length > 0;
    const notesLower = input.inspectorNotes.toLowerCase();
    const componentLower = (input.component ?? '').toLowerCase();
    const equipmentLower = (input.equipmentLabel ?? '').toLowerCase();
    const targetDesc = `${componentLower} ${equipmentLower} ${notesLower}`;

    // 2. Sensor telemetry analysis
    const latestAirQuality = input.recentSensorData.find((r) => r.airQuality != null)?.airQuality ?? 0;
    const latestTemp = input.recentSensorData.find((r) => r.temperature != null)?.temperature ?? 28;
    const latestHumidity = input.recentSensorData.find((r) => r.humidity != null)?.humidity ?? 55;
    const hasWaterLeakSensor = input.recentSensorData.some((r) => r.waterLeak);
    const hasFireSensor = input.recentSensorData.some((r) => r.fireDetected);
    const hasHighAirQuality = latestAirQuality > 200 || input.recentSensorData.some((r) => (r.airQuality ?? 0) > 200);
    const hasHighTemp = latestTemp > 40 || input.recentSensorData.some((r) => (r.temperature ?? 0) > 42);

    // 3. Determine Specific Domain Category
    type DomainCategory =
      | 'WATER_LEAK'
      | 'CORROSION'
      | 'STRUCTURAL_DAMAGE'
      | 'THERMAL_FIRE'
      | 'GAS_CO2_LEAK'
      | 'EQUIPMENT_ISSUE'
      | 'ROUTINE';

    let category: DomainCategory = 'ROUTINE';

    // Strict priority routing based on explicit user intent, photo vision classification, and telemetry
    if (
      input.inspectionType === 'POSSIBLE_LEAK' ||
      hasWaterLeakSensor ||
      (visionDetectedLeak && leakConf > corrConf) ||
      (targetDesc.includes('water') || targetDesc.includes('leak') || targetDesc.includes('drip') || targetDesc.includes('puddle') || targetDesc.includes('moist'))
    ) {
      category = 'WATER_LEAK';
    } else if (
      input.inspectionType === 'CORROSION' ||
      (visionDetectedCorrosion && corrConf >= leakConf) ||
      (targetDesc.includes('rust') || targetDesc.includes('corros') || targetDesc.includes('oxid') || targetDesc.includes('flaking'))
    ) {
      category = 'CORROSION';
    } else if (
      input.inspectionType === 'DAMAGE' ||
      targetDesc.includes('crack') || targetDesc.includes('fracture') || targetDesc.includes('break') || targetDesc.includes('deform') || targetDesc.includes('dent')
    ) {
      category = 'STRUCTURAL_DAMAGE';
    } else if (
      hasFireSensor || hasHighTemp ||
      targetDesc.includes('fire') || targetDesc.includes('burn') || targetDesc.includes('smoke') || targetDesc.includes('spark') || targetDesc.includes('overheat')
    ) {
      category = 'THERMAL_FIRE';
    } else if (
      hasHighAirQuality ||
      (targetDesc.includes('co2') || targetDesc.includes('gas') || targetDesc.includes('fume') || targetDesc.includes('odor'))
    ) {
      category = 'GAS_CO2_LEAK';
    } else if (
      input.inspectionType === 'EQUIPMENT_ISSUE' ||
      targetDesc.includes('bearing') || targetDesc.includes('vibrat') || targetDesc.includes('noise') || targetDesc.includes('motor') || targetDesc.includes('alignment')
    ) {
      category = 'EQUIPMENT_ISSUE';
    } else if (visionDetectedCorrosion) {
      category = 'CORROSION';
    } else if (visionDetectedLeak) {
      category = 'WATER_LEAK';
    } else {
      category = 'ROUTINE';
    }

    // 4. Synthesize Findings, Indicators & Recommendations tailored to Category
    const visualIndicators: VisualIndicator[] = [];
    const findings: string[] = [];
    const possibleCauses: string[] = [];
    const recommendations: string[] = [];
    const evidence: EvidenceItem[] = [];

    const compLabel = input.component || input.equipmentLabel || 'Inspected Component';
    const locLabel = input.locationCode ? `[${input.locationCode}]` : `at ${input.equipmentLabel ?? 'unit'}`;

    if (hasImages) {
      evidence.push({
        source: 'image',
        description: `Deep feature extraction performed on ${imageInfo.length} photographic file(s)` +
          (visionCorrosionResult ? ` (Leak Detector: ${(leakConf * 100).toFixed(1)}%, Corrosion Detector: ${(corrConf * 100).toFixed(1)}%)` : ''),
        weight: 'high',
      });
    }

    if (hasNotes) {
      evidence.push({
        source: 'inspector_notes',
        description: `Inspector notes logged: "${input.inspectorNotes.slice(0, 100)}"`,
        weight: 'high',
      });
    }

    if (input.recentSensorData.length > 0) {
      evidence.push({
        source: 'sensor_data',
        description: `Environmental telemetry: Air Quality ${latestAirQuality.toFixed(0)} ppm, Temp ${latestTemp.toFixed(1)}°C, Humidity ${latestHumidity.toFixed(0)}%`,
        weight: hasHighAirQuality || hasWaterLeakSensor || hasFireSensor ? 'high' : 'medium',
      });
    }

    if (input.energyTrend) {
      evidence.push({
        source: 'energy_trend',
        description: `Energy trend classification: ${input.energyTrend.classification} (${input.energyTrend.deviationPct.toFixed(1)}% deviation)`,
        weight: input.energyTrend.classification !== 'NORMAL' ? 'high' : 'low',
      });
    }

    let riskLevel: AIRiskLevel = 'LOW';
    let confidence = 0.90;
    let narrative = '';
    let predictivePrognosis: any = undefined;

    switch (category) {
      case 'WATER_LEAK': {
        const conf = Math.max(0.92, leakConf);
        riskLevel = hasWaterLeakSensor || conf >= 0.90 ? 'CRITICAL' : 'HIGH';
        confidence = Number(conf.toFixed(2));

        visualIndicators.push({
          type: 'visible_leakage_indicator',
          description: `Active fluid seepage and moisture stream trajectory identified (${(conf * 100).toFixed(1)}% confidence)`,
          confidence: Number(conf.toFixed(2)),
          region: `${compLabel} lower sealing interface / drainage basin`,
        });

        visualIndicators.push({
          type: 'moisture_accumulation',
          description: 'Liquid pooling and damp boundary marks spreading along equipment perimeter',
          confidence: 0.89,
          region: 'Foundation base plate',
        });

        findings.push(
          `[FLUID_LEAK - ${riskLevel}]: Vision model detected active fluid seepage and moisture pooling (${(conf * 100).toFixed(1)}% confidence) around ${compLabel} ${locLabel}.`,
          `[EQUIPMENT_HAZARD - HIGH]: Fluid containment loss creates risk of hydraulic pressure collapse, motor stator water damage, and local substation floor flooding.`,
          hasWaterLeakSensor
            ? `[SENSOR_TELEMETRY - CRITICAL]: Hardware moisture probe in this zone is actively signaling liquid presence.`
            : `[SENSOR_TELEMETRY - MEDIUM]: Ambient humidity tracking at ${latestHumidity.toFixed(0)}% with zone temperature at ${latestTemp.toFixed(1)}°C.`
        );

        possibleCauses.push(
          'Mechanical shaft packing seal degradation from pressure cycles',
          'Elastomeric O-ring blowout due to hydraulic line water hammer',
          'Flange coupling bolt loosening along fluid conveyance line',
          'Condensation drain trap obstruction causing tray backflow'
        );

        recommendations.push(
          `Isolate fluid supply valve to ${compLabel} and relieve line pressure`,
          `Inspect and replace mechanical seal / elastomeric gasket on ${compLabel}`,
          'Clear drainage sump and verify liquid level float switches',
          'Re-torque pipe coupling bolts to manufacturer specified torque specification'
        );

        predictivePrognosis = visionLeakResult?.predictive_prognosis ?? {
          future_hazard: 'Pressurized Fluid Line Rupture & Substation Flooding',
          estimated_time_to_failure_days: 5,
          time_to_failure_range: '3 - 8 operating days',
          risk_trajectory: 'ACCELERATING',
          degradation_mechanism: 'Hydraulic pressure surges progressively widening elastomeric seal breach',
          critical_intervention_deadline: 'Within 48 hours',
          timeline: [
            { timeframe: '24 Hours', projected_risk: 'HIGH', estimated_probability_pct: 70, expected_condition: 'Droplet seepage transitions to continuous trickling stream along housing.' },
            { timeframe: '7 Days', projected_risk: 'CRITICAL', estimated_probability_pct: 92, expected_condition: 'Hydraulic pressure surges blow out packing seal; active drainage overflow.' },
            { timeframe: '14 Days', projected_risk: 'CRITICAL', estimated_probability_pct: 99, expected_condition: 'Full containment breach; high-volume liquid discharge and motor electrical short risk.' },
          ],
        };

        narrative = `Photographic evidence and telemetry for "${input.equipmentLabel ?? 'Equipment'}" confirms active fluid seepage and moisture pooling around ${compLabel} ${locLabel}. AI Vision Engine evaluates a ${(conf * 100).toFixed(1)}% confidence for fluid leak with accelerating failure trajectory. Time-to-failure prognosis forecasts complete gasket blow-out within ${predictivePrognosis.time_to_failure_range} if not remediated. Immediate seal replacement and drainage check recommended.`;
        break;
      }

      case 'CORROSION': {
        const conf = Math.max(0.88, corrConf);
        const hottest = visionCorrosionResult?.hottest_cell;
        const regionText = hottest ? `Sector [Grid Row ${hottest.row}, Col ${hottest.col}]` : `${compLabel} surface perimeter`;

        riskLevel = conf >= 0.90 ? 'HIGH' : 'MEDIUM';
        confidence = Number(conf.toFixed(2));

        visualIndicators.push({
          type: 'suspected_corrosion',
          description: `Surface oxidation, iron-oxide rust staining & localized pitting (${(conf * 100).toFixed(1)}% confidence)`,
          confidence: Number(conf.toFixed(2)),
          region: regionText,
        });

        visualIndicators.push({
          type: 'unusual_discoloration',
          description: 'Flaking protective barrier coating with micro-scale oxidation scaling',
          confidence: 0.86,
          region: `${compLabel} structural joint`,
        });

        findings.push(
          `[CORROSION - ${riskLevel}]: Vision ML model detected active surface oxidation & pitting (${(conf * 100).toFixed(1)}% confidence) on ${compLabel} ${locLabel} at ${regionText}.`,
          `[STRUCTURAL_INTEGRITY - MEDIUM]: Progressive metal oxidation reduces effective wall thickness and compromises protective coating barrier.`,
          `[SENSOR_TELEMETRY - LOW]: Environmental telemetry: Air Quality ${latestAirQuality.toFixed(0)} ppm, Humidity ${latestHumidity.toFixed(0)}%.`
        );

        possibleCauses.push(
          'Atmospheric moisture condensation accelerating electrochemical oxidation',
          'Protective zinc/epoxy coating deterioration from thermal expansion cycles',
          'Galvanic potential reaction at dissimilar metal contact points'
        );

        recommendations.push(
          `Perform mechanical wire-brush descaling and apply anti-corrosion primer to ${compLabel}`,
          `Conduct ultrasonic metal thickness gauging to verify minimum structural wall tolerance`,
          'Inspect moisture mitigation barriers and improve ventilation around component'
        );
        predictivePrognosis = undefined;

        narrative = `Photographic analysis of "${input.equipmentLabel ?? 'Equipment'}" reveals localized surface corrosion and oxidation scaling on ${compLabel} ${locLabel}. AI-assisted visual screening identifies suspected oxidation with ${(conf * 100).toFixed(1)}% screening confidence. No time-to-failure or corrosion-percentage estimate is presented; manual inspection and thickness verification are recommended.`;
        break;
      }

      case 'STRUCTURAL_DAMAGE': {
        riskLevel = 'HIGH';
        confidence = 0.92;

        visualIndicators.push({
          type: 'cracks',
          description: `Micro-fracture propagation and structural fatigue stress on ${compLabel}`,
          confidence: 0.92,
          region: 'Load-bearing casing / bracket',
        });

        visualIndicators.push({
          type: 'structural_deformation',
          description: 'Mechanical deformation consistent with excess torque or physical impact',
          confidence: 0.88,
          region: 'Mounting flange interface',
        });

        findings.push(
          `[STRUCTURAL_DAMAGE - HIGH]: Visual inspection identifies stress micro-cracking and material deformation on ${compLabel} ${locLabel}.`,
          `[FATIGUE_RISK - HIGH]: Continued cyclic mechanical vibration may accelerate crack propagation leading to sudden mechanical separation.`,
          `[SENSOR_CORRELATION - MEDIUM]: Current electrical load and vibration telemetry indicate operational stress on mechanical drivetrain.`
        );

        possibleCauses.push(
          'Cyclic fatigue from harmonic vibration resonance',
          'Excessive bolt pre-tensioning causing localized stress concentration',
          'Mechanical shock impact during load transitions'
        );

        recommendations.push(
          `Conduct non-destructive dye-penetrant or magnetic particle crack inspection on ${compLabel}`,
          `Reinforce structural mounting brackets and verify vibration isolator dampening`,
          'Perform laser alignment on shaft couplings to eliminate dynamic torque imbalance'
        );

        predictivePrognosis = {
          future_hazard: 'Catastrophic Mechanical Fracture & Housing Failure',
          estimated_time_to_failure_days: 12,
          time_to_failure_range: '8 - 18 operating days',
          risk_trajectory: 'PROGRESSIVE',
          degradation_mechanism: 'Stress concentration driving rapid micro-crack propagation under vibration load',
          critical_intervention_deadline: 'Within 5 operating days',
          timeline: [
            { timeframe: '72 Hours', projected_risk: 'MEDIUM', estimated_probability_pct: 45, expected_condition: 'Micro-fissures expand along stress concentration axis.' },
            { timeframe: '7 Days', projected_risk: 'HIGH', estimated_probability_pct: 78, expected_condition: 'Crack reaches critical depth; noticeable casing vibration and acoustic chatter.' },
            { timeframe: '14 Days', projected_risk: 'CRITICAL', estimated_probability_pct: 95, expected_condition: 'Full structural fracture; component dislodgement and emergency trip.' },
          ],
        };

        narrative = `Inspection of "${input.equipmentLabel ?? 'Equipment'}" indicates structural stress cracking and deformation on ${compLabel} ${locLabel}. The system forecasts a progressive fatigue propagation trajectory with ~${predictivePrognosis.estimated_time_to_failure_days} operating days remaining before critical fracture. Structural reinforcement and dye testing recommended immediately.`;
        break;
      }

      case 'THERMAL_FIRE': {
        riskLevel = 'CRITICAL';
        confidence = 0.95;

        visualIndicators.push({
          type: 'burn_marks',
          description: `Thermal discoloration and scorching on ${compLabel}`,
          confidence: 0.94,
          region: 'Terminal connection / stator casing',
        });

        visualIndicators.push({
          type: 'damaged_insulation',
          description: 'Hardened, blistered conductor dielectric insulation',
          confidence: 0.91,
          region: 'Wiring conduit junction',
        });

        findings.push(
          `[FIRE_HAZARD - CRITICAL]: Severe thermal heat stress and electrical scorch patterning detected on ${compLabel} ${locLabel}.`,
          `[SENSOR_TELEMETRY - CRITICAL]: Thermal telemetry registers ${latestTemp.toFixed(1)}°C with elevated current draw.`,
          `[EQUIPMENT_DAMAGE - CRITICAL]: Imminent risk of phase-to-phase arcing, stator burnout, and thermal ignition.`
        );

        possibleCauses.push(
          'Loose electrical terminal lugs generating high contact resistance',
          'Blocked ventilation ducting or thermal radiator fin clogging',
          'Internal winding short-circuit or stator bearing friction overheat'
        );

        recommendations.push(
          'De-energize circuit immediately and perform FLIR thermal imaging audit',
          'Re-torque all electrical power connections to manufacturer specifications',
          'Clean cooling airflow ducts and inspect motor fan impeller'
        );

        predictivePrognosis = {
          future_hazard: 'Electrical Arcing Ignition & Stator Burnout',
          estimated_time_to_failure_days: 3,
          time_to_failure_range: '1 - 5 operating days',
          risk_trajectory: 'ACCELERATING',
          degradation_mechanism: 'Thermal breakdown of conductor dielectric insulation leading to flashover arcing',
          critical_intervention_deadline: 'Within 24 hours',
          timeline: [
            { timeframe: '24 Hours', projected_risk: 'HIGH', estimated_probability_pct: 80, expected_condition: 'Dielectric insulation carbonization increases leakage current.' },
            { timeframe: '48 Hours', projected_risk: 'CRITICAL', estimated_probability_pct: 95, expected_condition: 'Terminal flashover arcing and localized insulation combustion.' },
          ],
        };

        narrative = `Critical thermal stress detected on "${input.equipmentLabel ?? 'Equipment'}" (${compLabel}). High temperature readings (${latestTemp.toFixed(1)}°C) combined with visual scorch patterning signal imminent electrical fire and burnout risk. Immediate power shutdown and maintenance dispatch required.`;
        break;
      }

      case 'GAS_CO2_LEAK': {
        riskLevel = 'HIGH';
        confidence = 0.91;

        visualIndicators.push({
          type: 'visible_leakage_indicator',
          description: 'Flange perimeter residue pattern consistent with pressurized gas release',
          confidence: 0.88,
          region: 'Flange joint / valve gland seal',
        });

        findings.push(
          `[GAS_LEAK - HIGH]: Environmental air quality sensors register elevated gas density (${latestAirQuality.toFixed(0)} ppm) near ${compLabel} ${locLabel}.`,
          `[HAZARD_WARNING - HIGH]: Pressurized gas escaping through micro-gaps in valve packing creates air quality non-compliance and health hazards.`,
          `[SENSOR_TELEMETRY - HIGH]: MQ-135 sensor in this sector exceeded the 200 ppm threshold.`
        );

        possibleCauses.push(
          'Gland packing compression loss on control valve spindle',
          'Thermal expansion micro-separation at pipe flange gasket interface',
          'Pressure relief valve diaphragm pinhole leak'
        );

        recommendations.push(
          'Deploy portable acoustic leak detector and sniffer probe around valve flanges',
          'Tighten valve packing gland nuts evenly to restore compression seal',
          'Verify zone ventilation fan operation to disperse stagnant vapor accumulation'
        );

        predictivePrognosis = {
          future_hazard: 'Flange Seal Breach & Toxic/CO2 Gas Dispersion',
          estimated_time_to_failure_days: 8,
          time_to_failure_range: '4 - 12 operating days',
          risk_trajectory: 'ACCELERATING',
          degradation_mechanism: 'High-pressure gas erosion degrading packing elastomer matrix',
          critical_intervention_deadline: 'Within 48 hours',
          timeline: [
            { timeframe: '48 Hours', projected_risk: 'HIGH', estimated_probability_pct: 65, expected_condition: 'Micro-leak expands into audible gas hiss; localized gas density rises.' },
            { timeframe: '7 Days', projected_risk: 'CRITICAL', estimated_probability_pct: 90, expected_condition: 'Complete gasket seat failure; safety shutdown triggered by gas sensor array.' },
          ],
        };

        narrative = `Gas / CO2 safety advisory for "${input.equipmentLabel ?? 'Equipment'}": MQ-135 sensors indicate elevated concentration (${latestAirQuality.toFixed(0)} ppm) with visual residue along ${compLabel} ${locLabel}. Prognosis forecasts progressive containment loss within ${predictivePrognosis.time_to_failure_range}. Immediate gland tightening and acoustic leak testing required.`;
        break;
      }

      case 'EQUIPMENT_ISSUE': {
        riskLevel = 'MEDIUM';
        confidence = 0.88;

        visualIndicators.push({
          type: 'deterioration',
          description: `Mechanical wear and drive coupling misalignment indicators on ${compLabel}`,
          confidence: 0.87,
          region: 'Drive assembly / bearing housing',
        });

        findings.push(
          `[EQUIPMENT_ISSUE - MEDIUM]: Mechanical analysis indicates operational degradation and mechanical wear on ${compLabel} ${locLabel}.`,
          `[VIBRATION_MONITORING - MEDIUM]: Drive assembly shows elevated harmonic vibration consistent with bearing raceway fatigue.`,
          `[TELEMETRY_STATUS - LOW]: Environmental metrics: Air Quality ${latestAirQuality.toFixed(0)} ppm, Temperature ${latestTemp.toFixed(1)}°C.`
        );

        possibleCauses.push(
          'Lubricant breakdown or contamination inside bearing housing',
          'Shaft angular misalignment across flexible coupling',
          'Belt tension relaxation causing rotational slip'
        );

        recommendations.push(
          `Replenish synthetic grease in bearing housing of ${compLabel}`,
          `Check shaft alignment using dial indicators or laser alignment tool`,
          'Inspect belt tension and adjust idler pulley position'
        );

        predictivePrognosis = {
          future_hazard: 'Mechanical Bearing Seizure & Drivetrain Lockup',
          estimated_time_to_failure_days: 20,
          time_to_failure_range: '14 - 30 operating days',
          risk_trajectory: 'PROGRESSIVE',
          degradation_mechanism: 'Dry boundary friction accelerating bearing ball/raceway spalling',
          critical_intervention_deadline: 'Within 10 operating days',
          timeline: [
            { timeframe: '7 Days', projected_risk: 'MEDIUM', estimated_probability_pct: 40, expected_condition: 'Bearing noise and vibration harmonics increase under full load.' },
            { timeframe: '21 Days', projected_risk: 'HIGH', estimated_probability_pct: 80, expected_condition: 'Elevated friction temperature; cage cracking and noticeable shaft wobble.' },
            { timeframe: '45 Days', projected_risk: 'CRITICAL', estimated_probability_pct: 98, expected_condition: 'Total bearing seizure causing motor overcurrent trip and mechanical jam.' },
          ],
        };

        narrative = `Mechanical evaluation for "${input.equipmentLabel ?? 'Equipment'}" highlights progressive drive-train wear on ${compLabel} ${locLabel}. Time-to-failure prognosis indicates ~${predictivePrognosis.estimated_time_to_failure_days} operating days before bearing seizure risks. Re-lubrication and alignment recommended.`;
        break;
      }

      default: {
        riskLevel = 'LOW';
        confidence = 0.86;

        visualIndicators.push({
          type: 'deterioration',
          description: `Standard surface wear within normal operational tolerances on ${compLabel}`,
          confidence: 0.85,
          region: 'General component exterior',
        });

        findings.push(
          `[ROUTINE_AUDIT - LOW]: Photographic and telemetry assessment of ${compLabel} ${locLabel} shows baseline operational condition with normal surface wear.`,
          `[TELEMETRY_STATUS - LOW]: Environmental parameters: Air Quality ${latestAirQuality.toFixed(0)} ppm, Temperature ${latestTemp.toFixed(1)}°C — all metrics within standard baseline.`,
          `[CONTAINMENT_INTEGRITY - OK]: No active leaks, thermal anomalies, or structural cracking detected.`
        );

        possibleCauses.push(
          'Routine operational aging and normal duty-cycle wear',
          'Standard environmental airborne dust deposition'
        );

        recommendations.push(
          'Continue scheduled preventive inspection cycles',
          'Maintain photographic baseline records for year-over-year degradation comparison'
        );

        predictivePrognosis = {
          future_hazard: 'Normal Operational Aging & Duty-Cycle Wear',
          estimated_time_to_failure_days: 90,
          time_to_failure_range: '60 - 120 operating days',
          risk_trajectory: 'STABLE',
          degradation_mechanism: 'Standard operational mechanical wear within design safety margins',
          critical_intervention_deadline: 'Next quarterly audit',
          timeline: [
            { timeframe: '30 Days', projected_risk: 'LOW', estimated_probability_pct: 10, expected_condition: 'Component operates smoothly within baseline operational envelope.' },
            { timeframe: '60 Days', projected_risk: 'LOW', estimated_probability_pct: 20, expected_condition: 'Minor surface dusting; seals and couplings remain fully tight.' },
            { timeframe: '90 Days', projected_risk: 'MEDIUM', estimated_probability_pct: 35, expected_condition: 'Standard service interval due for filter cleaning and lubrication check.' },
          ],
        };

        narrative = `Photographic evidence and environmental telemetry for "${input.equipmentLabel ?? 'Equipment'}" (${compLabel}) have been validated. The asset is operating with high structural integrity and nominal baseline telemetry. Routine monitoring to be maintained.`;
        break;
      }
    }

    // Predictive prognosis is kept in result.predictivePrognosis object without polluting findings list

    const result: AIInspectionResult = {
      riskLevel,
      confidence,
      findings,
      possibleCauses,
      recommendations,
      visualIndicators,
      evidence,
      narrative,
      disclaimer: DISCLAIMER,
      provider: 'mock',
      modelVersion: 'EcoWatch-Industrial-Vision-v2.5-Multimodal',
      analyzedAt: new Date().toISOString(),
      predictivePrognosis: category === 'CORROSION' ? undefined : predictivePrognosis,
    };

    return { success: true, data: result };
  }
}
