/**
 * EcoGen AI — OpenAI GPT-4o Provider
 * ─────────────────────────────────────────────────────────────────────────────
 * Implements AIInspectionProvider using GPT-4o (vision) via OpenAI API.
 * Images read from EcoGen uploadStore and sent as base64 data URIs.
 *
 * Environment variables:
 *   OPENAI_API_KEY      — OpenAI API key
 *   OPENAI_MODEL_NAME   — default: gpt-4o
 *   OPENAI_TIMEOUT_MS   — default: 45000
 *   OPENAI_MAX_TOKENS   — default: 2048
 */

import fs from 'fs';
import type {
  AIInspectionProvider,
  AIInspectionInput,
  AIAnalysisResponse,
  AIInspectionResult,
} from '../types';
import { buildVLMMessages } from '../prompts/inspectionPrompt';
import { validateRawResponse, buildError } from '../utils/responseValidator';
import { uploadStore } from '../../services/uploadStore';

const MODEL_VERSION_PREFIX = 'openai';

const DISCLAIMER =
  'This is an AI-assisted maintenance risk assessment generated by EcoWatch AI using OpenAI GPT-4o. ' +
  'It is intended to support — not replace — qualified human inspection decisions. ' +
  'All findings use hedged language (suspected, possible, risk of) and do not constitute ' +
  'definitive diagnosis or guaranteed failure prediction.';

export class OpenAIInspectionProvider implements AIInspectionProvider {
  readonly name = 'openai';

  private readonly apiKey: string;
  private readonly modelName: string;
  private readonly timeoutMs: number;
  private readonly maxTokens: number;
  private readonly endpoint = 'https://api.openai.com/v1/chat/completions';

  constructor() {
    this.apiKey    = process.env.OPENAI_API_KEY   ?? '';
    this.modelName = process.env.OPENAI_MODEL_NAME ?? 'gpt-4o';
    this.timeoutMs = parseInt(process.env.OPENAI_TIMEOUT_MS ?? '45000', 10);
    this.maxTokens = parseInt(process.env.OPENAI_MAX_TOKENS ?? '2048',  10);
  }

  isAvailable(): boolean {
    return this.apiKey.length > 0 && this.apiKey !== 'your-key-here';
  }

  async analyzeInspection(input: AIInspectionInput): Promise<AIAnalysisResponse> {
    if (!this.isAvailable()) {
      return buildError('PROVIDER_UNAVAILABLE', 'OpenAI provider is not configured. Set OPENAI_API_KEY.', false);
    }

    // Load images from EcoGen uploadStore → base64 data URIs
    const imageDataUris: string[] = [];
    for (const storagePath of input.imageReferences) {
      try {
        if (uploadStore.exists(storagePath)) {
          const absPath = uploadStore.resolve(storagePath);
          const ext     = absPath.split('.').pop()?.toLowerCase() ?? 'jpeg';
          const mime    = ext === 'png' ? 'image/png' : ext === 'webp' ? 'image/webp' : 'image/jpeg';
          const buf     = fs.readFileSync(absPath);
          imageDataUris.push(`data:${mime};base64,${buf.toString('base64')}`);
        }
      } catch {
        // Non-fatal
      }
    }

    const messages = buildVLMMessages(input, imageDataUris);

    const requestBody = {
      model:           this.modelName,
      messages,
      max_tokens:      this.maxTokens,
      temperature:     0.1,
      response_format: { type: 'json_object' },
    };

    const controller    = new AbortController();
    const timeoutHandle = setTimeout(() => controller.abort(), this.timeoutMs);

    let rawResponse: string;
    let usedModel = this.modelName;

    try {
      const response = await fetch(this.endpoint, {
        method:  'POST',
        headers: {
          'Content-Type':  'application/json',
          'Authorization': `Bearer ${this.apiKey}`,
          'User-Agent':    'EcoWatch-AI/1.0',
        },
        body:   JSON.stringify(requestBody),
        signal: controller.signal,
      });

      clearTimeout(timeoutHandle);

      if (!response.ok) {
        const errorText = await response.text().catch(() => '');
        const code = response.status === 429 ? 'RATE_LIMITED' : 'PROVIDER_UNAVAILABLE';
        return buildError(code, `OpenAI API HTTP ${response.status}: ${errorText.slice(0, 200)}`, response.status >= 500 || response.status === 429);
      }

      const json = await response.json() as { model?: string; choices?: Array<{ message: { content: string } }> };
      if (!json.choices || json.choices.length === 0) {
        return buildError('MALFORMED_RESPONSE', 'OpenAI API returned no choices.', false);
      }

      rawResponse = json.choices[0].message.content;
      usedModel   = json.model ?? this.modelName;
    } catch (err: unknown) {
      clearTimeout(timeoutHandle);
      if (err instanceof Error && err.name === 'AbortError') {
        return buildError('TIMEOUT', `OpenAI timed out after ${this.timeoutMs}ms`, true);
      }
      const message = err instanceof Error ? err.message : String(err);
      return buildError('PROVIDER_UNAVAILABLE', `Network error calling OpenAI: ${message}`, true);
    }

    const validation = validateRawResponse(rawResponse);
    if (!validation.output?.riskLevel) {
      return buildError('MALFORMED_RESPONSE', `OpenAI response validation failed: ${validation.errors.join('; ')}`, false);
    }

    const p = validation.output;
    const output: AIInspectionResult = {
      riskLevel:        p.riskLevel       ?? 'UNKNOWN',
      confidence:       p.confidence      ?? 0.5,
      findings:         p.findings        ?? [],
      possibleCauses:   p.possibleCauses  ?? [],
      recommendations:  p.recommendations ?? [],
      visualIndicators: p.visualIndicators ?? [],
      evidence:         p.evidence        ?? [],
      narrative:        p.narrative       ?? 'AI analysis completed.',
      modelVersion:     `${MODEL_VERSION_PREFIX}/${usedModel}`,
      disclaimer:       DISCLAIMER,
      analyzedAt:       new Date().toISOString(),
      provider:         'openai',
    };

    return { success: true, data: output };
  }
}
