/**
 * EcoGen AI — Qwen3-VL Provider
 * ─────────────────────────────────────────────────────────────────────────────
 * Implements AIInspectionProvider using Qwen3-VL via OpenAI-compatible API.
 * Images are read from EcoGen's uploadStore and sent as base64 data URIs.
 *
 * Environment variables:
 *   QWEN_API_BASE_URL   — e.g. https://dashscope.aliyuncs.com/compatible-mode/v1
 *   QWEN_API_KEY        — DashScope API key
 *   QWEN_MODEL_NAME     — default: qwen-vl-max-latest
 *   QWEN_TIMEOUT_MS     — default: 30000
 *   QWEN_MAX_TOKENS     — default: 2048
 */

import fs from 'fs';
import type {
  AIInspectionProvider,
  AIInspectionInput,
  AIAnalysisResponse,
  AIInspectionResult,
} from '../types';
import { buildVLMMessages } from '../prompts/inspectionPrompt';
import { validateRawResponse, buildError } from '../utils/responseValidator';
import { uploadStore } from '../../services/uploadStore';

const MODEL_VERSION_PREFIX = 'qwen3-vl';

const DISCLAIMER =
  'This is an AI-assisted maintenance risk assessment generated by EcoWatch AI using the Qwen3-VL ' +
  'vision-language model. It is intended to support — not replace — qualified human inspection decisions. ' +
  'All findings use hedged language (suspected, possible, risk of) and do not constitute ' +
  'definitive diagnosis or guaranteed failure prediction.';

export class QwenAIInspectionProvider implements AIInspectionProvider {
  readonly name = 'qwen';

  private readonly apiBaseUrl: string;
  private readonly apiKey: string;
  private readonly modelName: string;
  private readonly timeoutMs: number;
  private readonly maxTokens: number;

  constructor() {
    this.apiBaseUrl = (process.env.QWEN_API_BASE_URL ?? '').replace(/\/$/, '');
    this.apiKey     = process.env.QWEN_API_KEY ?? '';
    this.modelName  = process.env.QWEN_MODEL_NAME ?? 'qwen-vl-max-latest';
    this.timeoutMs  = parseInt(process.env.QWEN_TIMEOUT_MS  ?? '30000', 10);
    this.maxTokens  = parseInt(process.env.QWEN_MAX_TOKENS  ?? '2048',  10);
  }

  isAvailable(): boolean {
    return this.apiBaseUrl.length > 0 && this.apiKey.length > 0 && this.apiKey !== 'your-key-here';
  }

  async analyzeInspection(input: AIInspectionInput): Promise<AIAnalysisResponse> {
    if (!this.isAvailable()) {
      return buildError(
        'PROVIDER_UNAVAILABLE',
        'Qwen AI provider is not configured. Set QWEN_API_BASE_URL and QWEN_API_KEY.',
        false
      );
    }

    // Load images from EcoGen uploadStore → base64 data URIs
    const imageDataUris: string[] = [];
    for (const storagePath of input.imageReferences) {
      try {
        if (uploadStore.exists(storagePath)) {
          const absPath  = uploadStore.resolve(storagePath);
          const ext      = absPath.split('.').pop()?.toLowerCase() ?? 'jpeg';
          const mime     = ext === 'png' ? 'image/png' : ext === 'webp' ? 'image/webp' : 'image/jpeg';
          const buf      = fs.readFileSync(absPath);
          imageDataUris.push(`data:${mime};base64,${buf.toString('base64')}`);
        }
      } catch {
        // Non-fatal — analysis continues without this image
      }
    }

    const messages = buildVLMMessages(input, imageDataUris);
    const endpoint = `${this.apiBaseUrl}/chat/completions`;

    const requestBody = {
      model:           this.modelName,
      messages,
      max_tokens:      this.maxTokens,
      temperature:     0.1,
      top_p:           0.9,
      response_format: { type: 'json_object' },
    };

    const controller    = new AbortController();
    const timeoutHandle = setTimeout(() => controller.abort(), this.timeoutMs);

    let rawResponse: string;
    let usedModel = this.modelName;

    try {
      const response = await fetch(endpoint, {
        method:  'POST',
        headers: {
          'Content-Type':  'application/json',
          'Authorization': `Bearer ${this.apiKey}`,
          'User-Agent':    'EcoWatch-AI/1.0',
        },
        body:   JSON.stringify(requestBody),
        signal: controller.signal,
      });

      clearTimeout(timeoutHandle);

      if (!response.ok) {
        const errorText = await response.text().catch(() => '');
        const code = response.status === 429 ? 'RATE_LIMITED' : 'PROVIDER_UNAVAILABLE';
        return buildError(code, `Qwen API HTTP ${response.status}: ${errorText.slice(0, 200)}`, response.status >= 500 || response.status === 429);
      }

      const json = await response.json() as { model?: string; choices?: Array<{ message: { content: string } }> };
      if (!json.choices || json.choices.length === 0) {
        return buildError('MALFORMED_RESPONSE', 'Qwen API returned no choices.', false);
      }

      rawResponse = json.choices[0].message.content;
      usedModel   = json.model ?? this.modelName;
    } catch (err: unknown) {
      clearTimeout(timeoutHandle);
      if (err instanceof Error && err.name === 'AbortError') {
        return buildError('TIMEOUT', `Qwen API timed out after ${this.timeoutMs}ms`, true);
      }
      const message = err instanceof Error ? err.message : String(err);
      return buildError('PROVIDER_UNAVAILABLE', `Network error calling Qwen: ${message}`, true);
    }

    const validation = validateRawResponse(rawResponse);
    if (!validation.output?.riskLevel) {
      return buildError('MALFORMED_RESPONSE', `Qwen response validation failed: ${validation.errors.join('; ')}`, false);
    }

    const p = validation.output;
    const output: AIInspectionResult = {
      riskLevel:        p.riskLevel       ?? 'UNKNOWN',
      confidence:       p.confidence      ?? 0.5,
      findings:         p.findings        ?? [],
      possibleCauses:   p.possibleCauses  ?? [],
      recommendations:  p.recommendations ?? [],
      visualIndicators: p.visualIndicators ?? [],
      evidence:         p.evidence        ?? [],
      narrative:        p.narrative       ?? 'AI analysis completed.',
      modelVersion:     `${MODEL_VERSION_PREFIX}/${usedModel}`,
      disclaimer:       DISCLAIMER,
      analyzedAt:       new Date().toISOString(),
      provider:         'qwen',
    };

    return { success: true, data: output };
  }
}
